export const WEATHERDATA_FETCH_REQUEST = "WEATHERDATA_FETCH_REQUEST";
export const WEATHERDATA_FETCH_SUCCESS = "WEATHERDATA_FETCH_SUCCESS";
export const WEATHERDATA_FETCH_ERROR = "WEATHERDATA_FETCH_ERROR";

export const DISCARD_ERROR = "DISCARD_ERROR";

export const SET_HIDE = "SET_HIDE";
export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";

export const AUTOCOMPLETE = "AUTOCOMPLETE";
export const GET_SUGGESTIONS_DATA = "GET_SUGGESTIONS_DATA";
